# Generated by Django 3.0 on 2021-04-18 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210418_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='value',
            new_name='amount',
        ),
    ]
